"use client"
import { useState } from "react"
import { Sidebar } from "@/components/sidebar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

export default function CRMIntegrationPage() {
  const [isConfigured, setIsConfigured] = useState(false)
  const [zapierKey, setZapierKey] = useState("")
  const [leads, setLeads] = useState([
    { id: 1, name: "John Doe", email: "john@example.com", source: "Website", date: "2025-02-06" },
    { id: 2, name: "Jane Smith", email: "jane@example.com", source: "LinkedIn", date: "2025-02-06" },
    { id: 3, name: "Bob Johnson", email: "bob@example.com", source: "Referral", date: "2025-02-06" },
  ])

  const handleConfigure = () => {
    // In a real application, you would validate the Zapier key and set up the integration
    setIsConfigured(true)
  }

  return (
    <div className="min-h-screen bg-gray-100">
      <div className="flex pt-16">
        {" "}
        {/* Added pt-16 to account for the fixed Navbar */}
        <Sidebar />
        <main className="flex-1 p-8 text-black">
          <h1 className="text-3xl font-bold mb-8 text-black">CRM Integration</h1>

          {!isConfigured ? (
            <Card>
              <CardHeader>
                <CardTitle>Configure Zapier Integration</CardTitle>
                <CardDescription>Connect your CRM pipeline through Zapier</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center space-x-4">
                  <Input
                    placeholder="Enter your Zapier API key"
                    value={zapierKey}
                    onChange={(e) => setZapierKey(e.target.value)}
                  />
                  <Button onClick={handleConfigure}>Configure</Button>
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardHeader>
                <CardTitle>Potential Leads</CardTitle>
                <CardDescription>List of potential leads generated by CRM</CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Email</TableHead>
                      <TableHead>Source</TableHead>
                      <TableHead>Date</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {leads.map((lead) => (
                      <TableRow key={lead.id}>
                        <TableCell>{lead.name}</TableCell>
                        <TableCell>{lead.email}</TableCell>
                        <TableCell>{lead.source}</TableCell>
                        <TableCell>{lead.date}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}
        </main>
      </div>
    </div>
  )
}

